US8 Syamned
juskis4/ViaEventAssociation pull request #22
Opened 2024-03-17 21:38 UTC by Semo0

2024-03-19 14:00 UTC, juskis4 requested changes

2024-03-19 14:00 UTC, juskis4 commented on UnitTests/Features/Event/ActivateEvent/ActivateEventTests.cs
> +    public void ReadiesEvent_ValidDataAndActiveStatus_ReturnsSuccess()
lets try to keep our guidelines, so change the test cases names to ReturnsSuccessResult or ReturnsFailureResult

2024-03-19 14:00 UTC, juskis4 commented on ViaEventAssociation.Core.Domain/Aggregates/ViaEvents/ViaEvent.cs
> +    public Result Readies ()
This method is more like a boolean method, so rename it to IsEventReady or IsReady

2024-03-23 13:25 UTC, Semo0 commented on ViaEventAssociation.Core.Domain/Aggregates/ViaEvents/ViaEvent.cs
> +    public Result Readies ()
Actually, it sets the event to ready status and the teacher used this name in the US.

2024-03-24 11:54 UTC, juskis4 approved these changes

2024-03-24 11:56 UTC, merged