Uc10_12 implemtation
juskis4/ViaEventAssociation pull request #34
Opened 2024-04-01 16:56 UTC by kimintor

implemented handlers  and commands added guest factory

2024-04-01 19:01 UTC, Semo0 requested changes

2024-04-01 19:01 UTC, Semo0 commented on UnitTests/Features/Guest/GuestFactory.cs
> +    public static Result<ViaEventAssociation.Core.Domain.Aggregates.Guests.Guest> CreateDefaultGuest()
use using instead.
using ViaEventAssociation.Core.Domain.Aggregates.Guests.

2024-04-04 09:24 UTC, Semo0 requested changes

2024-04-04 09:24 UTC, Semo0 commented on UnitTests/Features/Event/CancelParticipation/CancelParticipationHandlerTests.cs
> +    public void CancelParticipation_EventInReadyStatus_ReturnsSuccess()
Trolse said that we need test dor commands and test for handlers try to separate them.

2024-04-06 21:10 UTC, Semo0 approved these changes

2024-04-06 21:10 UTC, juskis4 approved these changes

2024-04-06 21:11 UTC, merged